name: 'Vitepress deploy'
description: 'A GitHub Action to build and publish Vitepress sites to GitHub Pages'
author: 'MashyG'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'gray-dark'
