name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: MashyG/blog@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: MashyG/blog
          TARGET_BRANCH: master
          BUILD_SCRIPT: pnpm && pnpm build
          BUILD_DIR: docs/.vuepress/dist
