name: Build and Deploy
on: [push]

# 使用并发取消任何当前作业或运行
concurrency:
  group: ${{github.ref}}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: MashyG/blog@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_ACTOR: MashyG
          TARGET_REPO: MashyG/blog
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist
