name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: MashyG/blog@master
        env:
          GITHUB_WORKSPACE: -
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_ACTOR: MashyG
          TARGET_REPO: MashyG/blog
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: npm install pnpm && pnpm && pnpm build
          BUILD_DIR: docs/.vuepress/dist
