name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: use pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.15.1

      - name: vuepress-deploy
        uses: MashyG/blog@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_ACTOR: MashyG
          TARGET_REPO: MashyG/blog
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: pnpm && pnpm build
          BUILD_DIR: docs/.vuepress/dist
